
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Behice BAKIR
 */
public class personelpayment extends javax.swing.JFrame {

    /**
     * Creates new form personelpayment
     */
    public personelpayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id_area = new javax.swing.JTextField();
        elektrik = new javax.swing.JRadioButton();
        internet = new javax.swing.JRadioButton();
        telefon = new javax.swing.JRadioButton();
        dogalgaz = new javax.swing.JRadioButton();
        su = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Personel İd");

        elektrik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elektrik.setText("Elektrik");
        elektrik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elektrikActionPerformed(evt);
            }
        });

        internet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        internet.setText("İnternet");
        internet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internetActionPerformed(evt);
            }
        });

        telefon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telefon.setText("Telefon");
        telefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonActionPerformed(evt);
            }
        });

        dogalgaz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dogalgaz.setText("Doğalgaz");
        dogalgaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogalgazActionPerformed(evt);
            }
        });

        su.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        su.setText("Su");
        su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(internet)
                            .addComponent(elektrik, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefon)
                            .addComponent(dogalgaz)
                            .addComponent(su)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(id_area, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(elektrik)
                .addGap(18, 18, 18)
                .addComponent(internet)
                .addGap(18, 18, 18)
                .addComponent(telefon)
                .addGap(18, 18, 18)
                .addComponent(dogalgaz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(su)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_area, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elektrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elektrikActionPerformed
        String billname="elektrik";
        String id=id_area.getText();
       if(id.equals("")){
           JOptionPane.showMessageDialog(null, "Personel İd'nizi giriniz");
           personelpayment ppay=new personelpayment();
           ppay.setVisible(true);
       }
       else{
           BankPersonel bp=new BankPersonel(id);
           bp.payment(id,billname);
       }
    }//GEN-LAST:event_elektrikActionPerformed

    private void internetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internetActionPerformed
        String billname="internet";
        String id=id_area.getText();
       if(id.equals("")){
           JOptionPane.showMessageDialog(null, "Personel İd'nizi giriniz");
           personelpayment ppay=new personelpayment();
           ppay.setVisible(true);
       }
       else{
           BankPersonel bp=new BankPersonel(id);
           bp.payment(id,billname);
       }
    }//GEN-LAST:event_internetActionPerformed

    private void telefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonActionPerformed
        String billname="telefon";
        String id=id_area.getText();
       if(id.equals("")){
           JOptionPane.showMessageDialog(null, "Personel İd'nizi giriniz");
           personelpayment ppay=new personelpayment();
           ppay.setVisible(true);
       }
       else{
           BankPersonel bp=new BankPersonel(id);
           bp.payment(id,billname);
       }
    }//GEN-LAST:event_telefonActionPerformed

    private void dogalgazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogalgazActionPerformed
        String billname="dogalgaz";
        String id=id_area.getText();
       if(id.equals("")){
           JOptionPane.showMessageDialog(null, "Personel İd'nizi giriniz");
           personelpayment ppay=new personelpayment();
           ppay.setVisible(true);
       }
       else{
           BankPersonel bp=new BankPersonel(id);
           bp.payment(id,billname);
       }
    }//GEN-LAST:event_dogalgazActionPerformed

    private void suActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suActionPerformed
        String billname="su";
        String id=id_area.getText();
       if(id.equals("")){
           JOptionPane.showMessageDialog(null, "Personel İd'nizi giriniz");
           personelpayment ppay=new personelpayment();
           ppay.setVisible(true);
       }
       else{
           BankPersonel bp=new BankPersonel(id);
           bp.payment(id,billname);
       }
    }//GEN-LAST:event_suActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personelpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personelpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personelpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personelpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personelpayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton dogalgaz;
    private javax.swing.JRadioButton elektrik;
    private javax.swing.JTextField id_area;
    private javax.swing.JRadioButton internet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton su;
    private javax.swing.JRadioButton telefon;
    // End of variables declaration//GEN-END:variables
}
